interface ICountries {
  name: string;
  code: string;
}

export const countries: ICountries[] = [
  { name: "Argentina", code: "ARG" },
  { name: "Australia", code: "AUS" },
  { name: "Brazil", code: "BRA" },
  { name: "Canada", code: "CAN" },
  { name: "China", code: "CHN" },
  { name: "Colombia", code: "COL" },
  { name: "Denmark", code: "DNK" },
  { name: "Egypt", code: "EGY" },
  { name: "France", code: "FRA" },
  { name: "Germany", code: "DEU" },
  { name: "Greece", code: "GRC" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "IDN" },
  { name: "Iran", code: "IRN" },
  { name: "Ireland", code: "IRL" },
  { name: "Italy", code: "ITA" },
  { name: "Japan", code: "JPN" },
  { name: "Mexico", code: "MEX" },
  { name: "Netherlands", code: "NLD" },
  { name: "New Zealand", code: "NZL" },
  { name: "Nigeria", code: "NGA" },
  { name: "Norway", code: "NOR" },
  { name: "Pakistan", code: "PAK" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHL" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Russia", code: "RUS" },
  { name: "Saudi Arabia", code: "SAU" },
  { name: "South Africa", code: "ZAF" },
  { name: "South Korea", code: "KOR" },
  { name: "Spain", code: "ESP" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "CHE" },
  { name: "Taiwan", code: "TWN" },
  { name: "Thailand", code: "THA" },
  { name: "Turkey", code: "TUR" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "ARE" },
  { name: "United Kingdom", code: "GBR" },
  { name: "United States", code: "USA" },
  { name: "Venezuela", code: "VEN" },
  { name: "Vietnam", code: "VNM" },
  { name: "Yemen", code: "YEM" },
  { name: "Zimbabwe", code: "ZWE" },
];
